title: The On-Track Cover Band 

domain: on-track-band.github.io
url: 'http://on-track-band.github.io'

baseurl: '' 

name: 
tagline: Jetzt neu in München 
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Jetzt neu in München 
description_tiny: 'Telefon: +49 163 4645075'
email: info@on-track-band.de
# website: on-track-band.github.io # do not add http://
# linkedin: 
# github: 
# twitter:

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
